//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIBUMI_LAPTOP_INSYA_ALLAH_LANCAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public long id { get; set; }
        public Nullable<long> merek_id { get; set; }
        public string tipe { get; set; }
        public string deskripsi { get; set; }
        public string processor { get; set; }
        public string ram { get; set; }
        public string penyimpanan { get; set; }
        public string ukuran_layar { get; set; }
        public Nullable<long> stok { get; set; }
        public Nullable<long> gudang_id { get; set; }
        public Nullable<long> kondisi_id { get; set; }
        public Nullable<System.DateTime> tanggal_ditambahkan { get; set; }
        public Nullable<long> garansi_id { get; set; }
        public Nullable<System.DateTime> garansi_expired { get; set; }
        public Nullable<long> harga { get; set; }
    }
}
