//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIBUMI_LAPTOP_INSYA_ALLAH_LANCAR
{
    using System;
    using System.Collections.Generic;
    
    public partial class @return
    {
        public long id { get; set; }
        public Nullable<long> transaksi_id { get; set; }
        public Nullable<long> item_id { get; set; }
        public Nullable<System.DateTime> tanggal_return { get; set; }
        public string status_return { get; set; }
        public string keterangan { get; set; }
        public string alasan_return { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<long> harga_satuan_temp { get; set; }
        public Nullable<long> total_harga { get; set; }
        public Nullable<long> total_bayar_return { get; set; }
    }
}
